# Generated by Django 4.1.3 on 2022-12-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='nation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
